"""Registered parties from val.se

This file contains all registered Swedish parties, grabbed from val.se.
When importing votes from val.se, all votes on parties on this list are
excluded.

"""

def is_registered_party(party_name):
    if not isinstance(party_name, unicode):
        party_name = party_name.decode('utf-8')
    return party_name.lower() in REGISTERED_PARTIES_LOWERCASE

REGISTERED_PARTIES =[
 u'Aktiv Demokrati - Partiet f\xf6r kontinuerlig direktdemokrati (ad)',
 u'Allianspartiet/Medborgarens r\xf6st',
 u'Arbetarepartiet-Socialdemokraterna',
 u'Centerpartiet',
 u'Djurens parti',
 u'Enhet',
 u'Europeiska Arbetarpartiet-EAP',
 u'Feministiskt initiativ',
 u'Folkpartiet liberalerna',
 u'Frihetspartiet',
 u'H\xf6gerpartiet de konservativa',
 u'Junilistan',
 u'Kommunistiska Partiet',
 u'Kristdemokraterna',
 u'Kristna V\xe4rdepartiet',
 u'Landsbygdspartiet Oberoende',
 u'Libertas Sverige',
 u'Milj\xf6partiet de gr\xf6na',
 u'Moderaterna',
 u'Mosebackedemokraterna',
 u'Nationaldemokraterna',
 u'Nordisk Union',
 u'Norrl\xe4ndska Samlingspartiet',
 u'Ny Framtid',
 u'Partiet.se',
 u'Piratpartiet',
 u'Rikshush\xe5llarna',
 u'R\xe4ttvisepartiet Socialisterna',
 u'Sj\xf6bopartiet',
 u'Skattereformisterna',
 u'Sk\xe5nepartiet',
 u'Sociala Partiet (SP)',
 u'Socialistiska Partiet',
 u'SPI V\xe4lf\xe4rden',
 u'Spritpartiet',
 u'Svenska F\xf6rnufts Partiet (SFP)',
 u'Svenskarnas parti',
 u'Sverigedemokraterna',
 u'V\xe4gvalet',
 u'V\xe4nsterpartiet',
 u'Jongleringspartiet',
 u'Lifepartiet',
 u'Stockholmspartiet',
 u'Tuvan',
 u'Upplands sjukv\xe5rdsparti',
 u'V\xe5rd f\xf6r pengarna',
 u'Vrinnevilistan',
 u'Invandrarpartiet Sverige',
 u'MedborgarForum',
 u'Socialisterna-V\xe4lf\xe4rdspartiet',
 u'Blekinge Sjukv\xe5rdsparti',
 u'Karlskronapartiet',
 u'BARAPARTIET',
 u'Kommunens Framtid',
 u'Sk\xe5ne l\xe4ns sjukv\xe5rdsparti',
 u'Sk\xe5nefederalisterna',
 u'Sk\xe5nes Sj\xe4lvst\xe4ndighetsparti',
 u'Sveriges Kommunistiska Parti (SKP)',
 u'Sveriges Nationella Demokratiska Parti',
 u'Visiona',
 u'V\xe5rdpartiet i Sk\xe5ne',
 u'Kungsbackaborna',
 u'Seniorpartiet',
 u'Missn\xf6jespartiet',
 u'Seniorpartiet',
 u'Sjukv\xe5rdspartiet - V\xe4stra G\xf6taland',
 u'Vi !',
 u'V\xe4lf\xe4rdspartiet',
 u'Sjukv\xe5rdspartiet i V\xe4rmland',
 u'\xd6rebropartiet',
 u'Oberoende Demokrater',
 u'Sjukv\xe5rdspartiet - V\xe4stmanland',
 u'Borl\xe4ngepartiet Dalarna',
 u'Dalarnas Sjukv\xe5rdsparti',
 u'Folkkampanjen f\xf6r sjukv\xe5rden',
 u'Omsorg f\xf6r alla',
 u'Sjukv\xe5rdspartiet G\xe4vleborg',
 u'Sjukv\xe5rdspartiet - V\xe4sternorrland',
 u'Sundsvalls framtid',
 u'Kirunapartiet',
 u'Knegarkampanjen',
 u'Norrbottens Frihandelsparti',
 u'Norrbottens Sjukv\xe5rdsparti',
 u'R\xe4dda V\xe5rden',
 u'Framtid V\xe4sby',
 u'V\xe4sbys b\xe4sta',
 u'Direktdemokraterna',
 u'ROSLAGSPARTIET \xd6ster\xe5kers st\xf6rsta, lokala parti',
 u'Skolpartiet i \xd6ster\xe5ker',
 u'\xd6ster\xe5kerspartiet',
 u'Nytta & Utveckling, partiet',
 u'\xd6partiet',
 u'Drevvikenpartiet',
 u'Huddingepartiet',
 u'Botkyrkapartiet',
 u'Tullingepartiet',
 u'R\xf6nningepartiet',
 u'Haninge Lokalparti',
 u'Nya Folkhemmet',
 u'Nykvarnspartiet',
 u'T\xe4bys Ungdomars Intresseparti',
 u'Sollentunapartiet',
 u'Etanolpartiet',
 u'Fria Stockholmare',
 u'Popvox',
 u'J\xe4rna Partiet',
 u'Pension\xe4rspartiet i S\xf6dert\xe4lje',
 u'Realist Partiet',
 u'S\xf6dert\xe4ljepartiet',
 u'Nackalistan',
 u'Bergshamrapartiet',
 u'BUS-partiet',
 u'Liding\xf6partiet',
 u'Waxholmspartiet - borgerligt alternativ',
 u'Partiet Roslagens Framtid',
 u'Roslagens oberoende parti',
 u'Aktion f\xf6r Sigtuna kommun',
 u'Sigtunapartiet Samling f\xf6r Sigtuna',
 u'Pension\xe4rspartiet i Nyn\xe4shamns kommun',
 u'Sorundanet Nyn\xe4shamns kommunparti',
 u'Kommunens V\xe4l',
 u'Knivsta.Nu',
 u'Det Lokala Partiet i Heby kommun',
 u'Fokus Enk\xf6ping',
 u'Nystart Enk\xf6ping (NE)',
 u'Borgerligt Alternativ',
 u'V\xe4gen till Livskvalitet',
 u'Alternativ 2000',
 u'Unionspartiet',
 u'Framtidsdemokraterna',
 u'Join The Parti',
 u'Granskningspartiet',
 u'Str\xe4ngn\xe4spartiet',
 u'Trosa Radikaler (Vagnh\xe4rad - V\xe4sterljung - Trosa)',
 u'\xd6desh\xf6gs Partiet',
 u'Kopparpartiet',
 u'Nybyggarpartiet',
 u'Bjorn',
 u'Folkfronten',
 u'Spiritvs Neronis',
 u'Nils Dacke partiet',
 u'Solidaritet, Arbete, Fred, Ekologi, SAFE',
 u'Vetlanda fram\xe5tanda',
 u'WetlandaListan',
 u'Tingsrydsalternativet',
 u'Alvesta Alternativet',
 u'Kommunens B\xe4sta (partipolitiskt obunden lista)',
 u'Tors\xe5spartiet',
 u'\xd6landspartiet s\xf6dra',
 u'Kommunpartiet VDM',
 u'Framtid \xd6land',
 u'nya \xd6landspartiet',
 u'Gottlandspartiet Gotlands framtid',
 u'Ronnebypartiet',
 u'Staffanstorpspartiet',
 u'Burl\xf6vs V\xe4l',
 u'Nya Listan i Vellinge',
 u'Framtidspartiet',
 u'F\xf6ryngringspartiet (FYP)',
 u'Kommunens V\xe4l',
 u'Barn- och Ungdomspartiet i Sj\xf6bo',
 u'Kommunpartiet i Sj\xf6bo',
 u'H\xf6rbypartiet',
 u'Medborgarpartiet i H\xf6rby',
 u'SOS Tomelilla',
 u'Alternativet',
 u'G\xf6ingepartiet Kommunal Samling',
 u'Perstorps Framtid',
 u'Bj\xe4repartiet',
 u'Ansvarspartiet',
 u'Gula Partiet',
 u'Kommunisterna',
 u'Malm\xf6partiet',
 u'Demokratisk V\xe4nster i Lund',
 u'F\xf6rNyaLund',
 u'Helsingborgspartiet',
 u'\xc5ngf\xe4rjepartiet',
 u'Nya Kommunpartiet Esl\xf6v',
 u'Ystadspartiet',
 u'S\xf6dersl\xe4ttspartiet',
 u'Trelleborgs Skolparti',
 u'Kristianstadsbygdens Framtid',
 u'\xc5huspartiet',
 u'\xd6sterlenpartiet',
 u'EngelholmsPartiet',
 u'Folkets V\xe4l',
 u'Kommunens V\xe4l',
 u'Laholmspartiet',
 u'Samh\xe4llslistan Aktiv Politik',
 u'DIN FRAMTID',
 u'Kommunpartiet',
 u'Sportpartiet',
 u'Kommunalt Alternativ',
 u'Samh\xe4llets b\xe4sta',
 u'Folkviljan p\xe5 Orust',
 u'Orustpartiet (OP)',
 u'Nya Soten\xe4spartiet',
 u'Ale - demokraterna',
 u'Framtid i Ale',
 u'Framtidspartiet - f\xf6r h\xe5llbar utveckling',
 u'\xd6ppna Hela Lerum',
 u'Kommunpartiet v\xe5r framtid',
 u'Marks Oberoende Demokrater, MOD',
 u'Kommunens V\xe4l',
 u'Mitt i Sverige',
 u'Barnpartiet',
 u'Framtidspartiet Sverige',
 u'Normaldemokraterna',
 u'Torslandapartiet',
 u'\xd6ppna G\xf6teborg!',
 u'Utvecklingspartiet',
 u'Lysekilspartiet',
 u'Skaft\xf6partiet',
 u'Solidariskt Uddevalla',
 u'Str\xf6mstadspartiet',
 u'Bor\xe5svalet',
 u'Nya Ulricehamn',
 u'MariestadsPartiet',
 u'Det H\xe5llbara Alternativet',
 u'Kommunens B\xe4sta',
 u'Nordmarkspartiet',
 u'Hela Sunne',
 u'Karlstads Medborgarparti',
 u'Kvastpartiet',
 u'Framtidspartiet i Lekeberg',
 u'Lax\xe5partiet',
 u'Kraftsamling f\xf6r Ljusnarsberg',
 u'Norapartiet',
 u'Skinnskattebergsdemokraterna',
 u'Partiet f\xf6r Norbergs Framtid',
 u'V\xe4ster\xe5spartiet',
 u'Salas b\xe4sta',
 u'Omsorgspartiet i Arboga',
 u'Kommunpartiet - Vansbro',
 u'Malung-S\xe4lenpartiet',
 u'Kommunal Samling',
 u'Kommunlistan',
 u'Morapartiet',
 u'Falupartiet',
 u'Hedemorapartiet',
 u'L\xe5ngshyttepartiet',
 u'Kommunlistan',
 u'Bopartiet',
 u'Ljusdals Framtids Parti',
 u'Socialradikala Demokraterna',
 u'Ny Ordning (NO)-Partipolitiskt ob.',
 u'Bolln\xe4spartiet',
 u'V\xe5r Framtids politiska utskott',
 u'GPS - Gr\xf6nt Perspektiv i Sundsvall',
 u'Sundsvallspartiet',
 u'V\xe4strainitiativet Sollefte\xe5 Kommuns B\xe4sta',
 u'Allians f\xf6r Ragunda',
 u'R\xe4ttvis Demokrati',
 u'V\xe4stj\xe4mtlands V\xe4l',
 u'Bergspartiet',
 u'Folkets r\xf6st - VOX humana',
 u'H\xe4rjedalspartiet',
 u'Mal\xe5listan',
 u'Kommunlistan',
 u'Politiskt Alternativ',
 u'Opinion',
 u'\xc5sele kommunlista',
 u'\xc5selepartiet',
 u'Enighet R\xe4ttvisa Socialism Arbetarpartiet',
 u'Alternativet',
 u'Framtid i Jokkmokks kommun',
 u'Samernas V\xe4l',
 u'Framtid i Kalix',
 u'Kalixpartiet',
 u'Malmf\xe4ltens V\xe4l',
 u'Kommunisterna']


REGISTERED_PARTIES_LOWERCASE = [p.lower() for p in REGISTERED_PARTIES]
